### PR TITLE
Added possibility to save data/traces into simple js files, …

### LINKED ISSUE #2: Use data from file?
Is there a way to use the data (x,y) from a file, instead having all the coordinates in memory?

### PR DESCRIPTION
**Pull request by Ismoh**
…to be able to preserve memory usage.

Please have a look and decide, if you want to merge this.

If there is anything unclear, let me know. I'll update the PR then!

Thanks a ton & have a good one!

Resolves #2

### CODE REVIEW

**Comment by Ismoh** [comment]
As you may noticed in #2, I was searching for a really simple and stupid solution to serve traces in json format. To get rid of any CORS error or other javascript issues, I simply store json formatted javascript objects/variables in *.js files to import them with a script tag. Instead of setting up and running a local js server.

I tested this with 5 traces eaxh 12000 x,y points without any memory issues, because with this implementation you are able to add as many x and y values as you like:
I stored 100 points in memory and then wrote them into js files. The lua function for this appends those points if the trace with name "foo" already exists. See https://github.com/kenloen/plotly.lua/pull/3/files#diff-eb8cac223cb7c05e7abea6eeae17f927a8428af10f7436be8db830218f128bb6R360

Do you want me to add an example to the readme and rockspec?

**Comment by Ismoh** [comment]
Ping @kenloen :)

**Comment by Ismoh** [comment]
@kenloen if you don't like it, just close it, but please dont let it open forever.

**Comment by kenloen** [comment]
Sorry @Ismoh for the late response. 
Just browsed though for changes and it look good! 
I would be nice if you could add an example to the readme/rockspec. Then we can merge it afterwards.

**Comment by Ismoh** [comment]
> Sorry @Ismoh for the late response. Just browsed though for changes and it look good! I would be nice if you could add an example to the readme/rockspec. Then we can merge it afterwards.

Sure thing! Going to add this at the weekend!

**Comment by Ismoh** [comment]
I didn't forget this and will update the PR, just not sure about when! Keep it open!

**Pull request closed without merging**
